// GenshinImpact-Map-React/src/components/LocationBtn.tsx
import { useState } from "react";
import useMapStore from "../store/useMapStore";
import { useMapActions } from "../hook/useMapAction";
import type { AnchorListItem } from "../types/api/map.types";

export default function LocationBtn() {
  const mapAnchorList = useMapStore((state) => state.mapAnchorList);

  return (
    <div className="group top-[84px] -right-8 absolute flex justify-center items-center bg-[#323947cc] rounded-[8px] w-10 h-10 cursor-pointer">
      <div
        className="bg-cover w-6 h-6"
        style={{
          backgroundImage: `url('/images/map-icon/location-btn.png')`,
        }}
      ></div>
      <div className="invisible group-hover:visible top-0 left-[52px] absolute bg-[#3b4354] rounded-[12px] w-[230px] transition-all duration-500">
        <div className="!p-3 border-[#56617833] border-b font-bold text-[#d3bc8e] text-[16px]">
          快速定位
        </div>
        <div className="h-[500px] overflow-y-auto">
          {mapAnchorList &&
            mapAnchorList.map((item) => {
              return <AreaItem key={item.id} item={item} />;
            })}
        </div>
      </div>
    </div>
  );
}

function AreaItem({ item }: { item: AnchorListItem }) {
  const { flyTo } = useMapActions();
  const [isHovered, setIsHovered] = useState(false);
  function onAreaNameClick(item: AnchorListItem, zoom: number) {
    // 由于缺少官方数据，只能固定一个位置来演示快速定位
    const { lat = -120, lng = 145 } = item;
    flyTo([lat, lng], zoom);
  }
  return (
    <div className="area-item">
      <div
        className="flex items-center !pl-[15px] h-12 area-parent"
        onClick={() => onAreaNameClick(item, 5)}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
      >
        <div
          className="bg-cover !mr-[5px] w-3 h-3 parent-icon"
          style={{
            backgroundImage: `url('/images/map-icon/location-icon-${
              isHovered ? "h" : "n"
            }.png')`,
          }}
        ></div>
        <div
          className="font-normal text-[14px] parent-name"
          style={{
            color: isHovered ? "#ece5d8" : "#d3bc8e",
          }}
        >
          {item.name}
        </div>
      </div>
      {item.children.map((it) => {
        return (
          <div
            className="flex items-center !pl-8 h-12 font-normal text-[#ece6d9bf] hover:text-[#ece5d8] area-child"
            onClick={() => onAreaNameClick(it, 6)}
            key={it.id}
          >
            {it.name}
          </div>
        );
      })}
    </div>
  );
}

// GenshinImpact-Map-Vue/src/components/LocationBtn.vue
<script setup lang="ts">
import { globalDataInstance } from '../js/global-data'
import { useHomeStore } from '@/stores/home';
import type { AnchorListItem } from '@/types/api/map.types';
import { storeToRefs } from 'pinia';

const store = useHomeStore()
const { mapAnchorList } = storeToRefs(store)

function onAreaNameClick(item: AnchorListItem, zoom: number) {
  globalDataInstance.mapManager.flyTo([-120, 145], zoom)
}

</script>

<template>
  <div class="location-btn">
    <div class="location-icon"></div>
    <div class="location-content">
      <div class="location-content-title">快速定位</div>
      <div class="content-areas">
        <div class="area-item" v-for="item in mapAnchorList" :key="item.id">
          <div class="area-parent" @click="onAreaNameClick(item, 5)">
            <div class="parent-icon"></div>
            <div class="parent-name">{{ item.name }}</div>
          </div>
          <div class="area-child" @click="onAreaNameClick(it, 6)" v-for="it in item.children" :key="it.id"> {{ it.name
            }}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style lang="less" scoped>
.location-btn {
  position: absolute;
  top: 84px;
  right: -32px;
  width: 40px;
  height: 40px;
  background-color: rgba(50, 57, 71, .8);
  border-radius: 8px;
  cursor: pointer;
  display: flex;
  justify-content: center;
  align-items: center;

  &:hover {
    .location-content {
      visibility: visible;
    }
  }

  .location-icon {
    width: 24px;
    height: 24px;
    background-image: url('/images/map-icon/location-btn.png');
    background-size: cover;
  }

  .location-content {
    position: absolute;
    background: #3b4354;
    border-radius: 12px;
    top: 0;
    left: 52px;
    width: 230px;
    visibility: hidden;
    transition: all .5s;

    .location-content-title {
      font-size: 16px;
      color: #d3bc8e;
      padding: 12px;
      border-bottom: 1px solid rgba(86, 97, 120, .2);
      font-weight: bold;
    }

    .content-areas {
      height: 500px;
      overflow-y: auto;

      &::-webkit-scrollbar {
        display: none;
      }

      .area-item {
        .area-parent {
          display: flex;
          align-items: center;
          height: 48px;
          padding-left: 15px;

          &:hover {
            .parent-icon {
              background-image: url('/images/map-icon/location-icon-h.png');
            }

            .parent-name {
              color: #ece5d8;
            }
          }

          .parent-icon {
            width: 12px;
            height: 12px;
            background-image: url('/images/map-icon/location-icon-n.png');
            background-size: cover;
            margin-right: 5px;
          }

          .parent-name {
            color: #d3bc8e;
            font-size: 14px;
            font-weight: 400;
          }
        }

        .area-child {
          display: flex;
          align-items: center;
          height: 48px;
          font-weight: 400;
          color: hsla(39, 34%, 89%, .75);
          padding-left: 32px;

          &:hover {
            color: #ece5d8;
          }
        }
      }
    }
  }
}
</style>
